/* Generated by Yosys 0.57+148 (git sha1 259bd6fb3, g++ 11.4.0-1ubuntu1~22.04.2 -fPIC -O3) */

module adder(A, B, Cin, S, Cout);
  input A;
  wire A;
  input B;
  wire B;
  input Cin;
  wire Cin;
  output S;
  wire S;
  output Cout;
  wire Cout;
  wire _00_;
  wire _01_;
  wire _02_;
  wire _03_;
  wire _04_;
  wire _05_;
  wire _06_;
  wire _07_;
  wire _08_;
  wire _09_;
  sky130_fd_sc_hd__maj3_1 _10_ (
    .A(_01_),
    .B(_00_),
    .C(_02_),
    .X(_03_)
  );
  sky130_fd_sc_hd__xor3_1 _11_ (
    .A(_01_),
    .B(_00_),
    .C(_02_),
    .X(_04_)
  );
  assign _01_ = B;
  assign _00_ = A;
  assign _02_ = Cin;
  assign S = _04_;
  assign Cout = _03_;
endmodule
