/* Generated by Yosys 0.57+148 (git sha1 259bd6fb3, g++ 11.4.0-1ubuntu1~22.04.2 -fPIC -O3) */

module full_adder(A, B, Cin, S, Cout);
  input A;
  wire A;
  input B;
  wire B;
  input Cin;
  wire Cin;
  output S;
  wire S;
  output Cout;
  wire Cout;
  wire _00_;
  wire _01_;
  wire _02_;
  wire _03_;
  wire _04_;
  wire _05_;
  wire _06_;
  wire _07_;
  wire _08_;
  wire _09_;
  sky130_fd_sc_hd__maj3_1 _10_ (
    .A(_01_),
    .B(_00_),
    .C(_02_),
    .X(_03_)
  );
  sky130_fd_sc_hd__xor3_1 _11_ (
    .A(_01_),
    .B(_00_),
    .C(_02_),
    .X(_04_)
  );
  assign _01_ = B;
  assign _00_ = A;
  assign _02_ = Cin;
  assign S = _04_;
  assign Cout = _03_;
endmodule

module two_bit_adder(A, B, Cin, Cout, S);
  input [1:0] A;
  wire [1:0] A;
  input [1:0] B;
  wire [1:0] B;
  input Cin;
  wire Cin;
  output Cout;
  wire Cout;
  output [1:0] S;
  wire [1:0] S;
  wire C1;
  full_adder fa1 (
    .A(A[0]),
    .B(B[0]),
    .Cin(Cin),
    .Cout(C1),
    .S(S[0])
  );
  full_adder fa2 (
    .A(A[1]),
    .B(B[1]),
    .Cin(C1),
    .Cout(Cout),
    .S(S[1])
  );
endmodule
