/* Generated by Yosys 0.57+148 (git sha1 259bd6fb3, g++ 11.4.0-1ubuntu1~22.04.2 -fPIC -O3) */

module two_bit_adder(A, B, Cin, Cout, S);
  input [1:0] A;
  wire [1:0] A;
  input [1:0] B;
  wire [1:0] B;
  input Cin;
  wire Cin;
  output Cout;
  wire Cout;
  output [1:0] S;
  wire [1:0] S;
  wire _00_;
  wire _01_;
  wire _02_;
  wire _03_;
  wire _04_;
  wire _05_;
  wire _06_;
  wire _07_;
  wire _08_;
  wire _09_;
  wire _10_;
  wire _11_;
  wire _12_;
  wire _13_;
  wire _14_;
  wire _15_;
  wire _16_;
  wire _17_;
  wire _18_;
  wire _19_;
  wire _20_;
  wire _21_;
  wire _22_;
  wire \fa1.A ;
  wire \fa1.B ;
  wire \fa1.Cin ;
  wire \fa1.S ;
  wire \fa2.A ;
  wire \fa2.B ;
  wire \fa2.Cout ;
  wire \fa2.S ;
  sky130_fd_sc_hd__nand3_1 _23_ (
    .A(_13_),
    .B(_11_),
    .C(_15_),
    .Y(_22_)
  );
  sky130_fd_sc_hd__nor3_1 _24_ (
    .A(_13_),
    .B(_11_),
    .C(_15_),
    .Y(_19_)
  );
  sky130_fd_sc_hd__maj3_1 _25_ (
    .A(_13_),
    .B(_11_),
    .C(_15_),
    .X(_20_)
  );
  sky130_fd_sc_hd__o21ai_0 _26_ (
    .A1(_19_),
    .A2(_20_),
    .B1(_22_),
    .Y(_17_)
  );
  sky130_fd_sc_hd__maj3_1 _27_ (
    .A(_14_),
    .B(_12_),
    .C(_20_),
    .X(_16_)
  );
  sky130_fd_sc_hd__xnor2_1 _28_ (
    .A(_14_),
    .B(_12_),
    .Y(_21_)
  );
  sky130_fd_sc_hd__xnor2_1 _29_ (
    .A(_20_),
    .B(_21_),
    .Y(_18_)
  );
  assign S = { \fa2.S , \fa1.S  };
  assign \fa1.A  = A[0];
  assign \fa1.B  = B[0];
  assign \fa1.Cin  = Cin;
  assign \fa2.A  = A[1];
  assign \fa2.B  = B[1];
  assign \fa2.Cout  = Cout;
  assign _13_ = B[0];
  assign _11_ = A[0];
  assign _15_ = Cin;
  assign \fa1.S  = _17_;
  assign _14_ = B[1];
  assign _12_ = A[1];
  assign Cout = _16_;
  assign \fa2.S  = _18_;
endmodule
